### ISSUE TITLE
nvm usage

### ISSUE THREAD

**Issue by hyzhak** [kleinee/jns#15]
I got problem on using those script to setup `jupyter`, because I have been using `nvm`. I got error:
```
Traceback (most recent call last):

  File "/home/pi/.venv/jns/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 71, in start
    ans = self.run_task()

  File "/home/pi/.venv/jns/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 100, in run_task
    for arg in self.extra_args

  File "/home/pi/.venv/jns/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 100, in <listcomp>
    for arg in self.extra_args

  File "/home/pi/.venv/jns/lib/python3.5/site-packages/jupyterlab/commands.py", line 210, in install_extension
    return handler.install_extension(extension)

  File "/home/pi/.venv/jns/lib/python3.5/site-packages/jupyterlab/commands.py", line 347, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/home/pi/.venv/jns/lib/python3.5/site-packages/jupyterlab/commands.py", line 1095, in _install_extension
    info = self._extract_package(extension, tempdir)

  File "/home/pi/.venv/jns/lib/python3.5/site-packages/jupyterlab/commands.py", line 1132, in _extract_package
    ret = self._run([which('npm'), 'pack', source], cwd=tempdir)

  File "/home/pi/.venv/jns/lib/python3.5/site-packages/jupyterlab/jlpmapp.py", line 59, in which
    raise ValueError(msg)

ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.


Errored, use --debug for full output:
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
```
on 
```bash
jupyter labextension install @jupyter-widgets/jupyterlab-manager --debug
```
(I have attached `--debug` to get more information).
# How to solve
Actual solution is quite trivial:
```bash
ln -s `which npm` /usr/bin/npm
```

This solution could be useful for others, because I have spent an hour on searching this solution, but I don't know where I could place in this repository.

**Comment by kleinee** [comment]
@hyzhak: Thanks for letting me know! The script uses ```n-install``` which by default install into ```~``` .  I do agree that it would be nicer to have ```node``` and ```npm``` both installed in ```/usr/bin/```  as seems to be the case in your installation.  Looking at the GitHub repository of ```n``` at https://github.com/tj/n suggests that it is possible to change the install location. This may require require sudo. I will run a test over the weekend and if it works I can change ```conf_jupyter.sh``` accordingly.

**Comment by kleinee** [comment]
I close this for the moment and leave it to users of this repository to adopt ***@hyzhak's*** solution. Thanks again for posting it here!
